# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('innovosite', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('room', models.CharField(blank=True, max_length=256, null=True)),
                ('model_name', models.CharField(blank=True, max_length=256, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=256, null=True)),
                ('manufacturer_website', models.CharField(blank=True, max_length=256, null=True)),
                ('short_desc', models.CharField(blank=True, max_length=256, null=True)),
                ('full_desc', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('contact_1_name', models.CharField(blank=True, max_length=256, null=True)),
                ('contact_1_email', models.CharField(blank=True, max_length=256, null=True)),
                ('contact_2_name', models.CharField(blank=True, max_length=256, null=True)),
                ('contact_2_email', models.CharField(blank=True, max_length=256, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('date_of_purchase', models.DateTimeField(blank=True, null=True)),
                ('date_disposed_of', models.DateTimeField(blank=True, null=True)),
                ('date_archived', models.DateTimeField(blank=True, null=True)),
                ('end_of_life', models.DateTimeField(blank=True, null=True)),
                ('last_calibration_date', models.DateTimeField(blank=True, null=True)),
                ('next_calibration_date', models.DateTimeField(blank=True, null=True)),
                ('PAT', models.DateTimeField(blank=True, null=True)),
                ('acronym', models.CharField(blank=True, max_length=24, null=True)),
                ('archived', models.IntegerField(blank=True, default=0, null=True)),
                ('asset_no', models.CharField(blank=True, max_length=256, null=True)),
                ('availability', models.CharField(blank=True, max_length=256, null=True)),
                ('calibrated', models.CharField(blank=True, max_length=4, null=True)),
                ('copyright_notice', models.CharField(blank=True, max_length=256, null=True)),
                ('cost', models.CharField(blank=True, max_length=256, null=True)),
                ('embedded_content', models.TextField(blank=True, null=True)),
                ('finance_id', models.CharField(blank=True, max_length=256, null=True)),
                ('future_upgrades', models.TextField(blank=True, null=True)),
                ('is_disposed_of', models.CharField(blank=True, max_length=5, null=True)),
                ('is_parent', models.IntegerField(blank=True, default=0, null=True)),
                ('last_updated_username', models.CharField(blank=True, max_length=256, null=True)),
                ('last_updated_email', models.CharField(blank=True, max_length=256, null=True)),
                ('maintenance', models.CharField(blank=True, max_length=256, null=True)),
                ('portability', models.CharField(blank=True, max_length=256, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('quantity_detail', models.CharField(blank=True, max_length=256, null=True)),
                ('replacement_cost', models.CharField(blank=True, max_length=256, null=True)),
                ('restrictions', models.CharField(blank=True, max_length=256, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=256, null=True)),
                ('specification', models.TextField(blank=True, null=True)),
                ('supplier_id', models.IntegerField(blank=True, null=True)),
                ('technique', models.CharField(blank=True, max_length=256, null=True)),
                ('training_required', models.IntegerField(blank=True, null=True)),
                ('training_provided', models.IntegerField(blank=True, null=True)),
                ('upgrades', models.TextField(blank=True, null=True)),
                ('usergroup', models.CharField(blank=True, max_length=256, null=True)),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='innovosite.Building')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='innovosite.SubOrganization')),
                ('related_media', models.ManyToManyField(blank=True, to='core.DocumentFile')),
            ],
        ),
    ]
