# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='PAT',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='acronym',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='calibrated',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='copyright_notice',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='date_archived',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='date_disposed_of',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='embedded_content',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='end_of_life',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='finance_id',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='future_upgrades',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='is_disposed_of',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='is_parent',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='last_calibration_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='last_updated_email',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='last_updated_username',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='next_calibration_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='portability',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='quantity_detail',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='replacement_cost',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='restrictions',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='supplier_id',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='technique',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='training_provided',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='training_required',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='upgrades',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='usergroup',
        ),
    ]
