# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20160512_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='availability',
            field=models.CharField(choices=[('available', 'available'), ('under maintenance', 'under maintenance'), ('in-use', 'currently in use'), ('under repair', 'currently under repair'), ('not operational', 'not operational')], default='available', max_length=256, null=True),
        ),
    ]
