# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20160429_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='model',
            new_name='model_name',
        ),
    ]
