# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20160512_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
