# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20160502_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='PAT',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='acronym',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_no',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='availability',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='calibrated',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='contact_1_email',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='contact_1_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='contact_2_email',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='contact_2_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='copyright_notice',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cost',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_archived',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_disposed_of',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_of_purchase',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='embedded_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='end_of_life',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='finance_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='full_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='future_upgrades',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_disposed_of',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_calibration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_updated_email',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_updated_username',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='maintenance',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='manufacturer',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='manufacturer_website',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='next_calibration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='innovosite.SubOrganization'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='portability',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='quantity_detail',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='replacement_cost',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='restrictions',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='room',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_no',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='short_desc',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='specification',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='supplier_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='technique',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='training_provided',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='training_required',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='upgrades',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='usergroup',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='year_of_manufacture',
            field=models.IntegerField(null=True),
        ),
    ]
