# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20160502_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='archived',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_parent',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
