# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20160502_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
