# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20160502_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='innovosite.SubOrganization'),
        ),
    ]
