# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(blank=True, max_length=48, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Innovosite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('documents', models.ManyToManyField(related_name='site_documents', to='core.DocumentFile')),
            ],
        ),
        migrations.CreateModel(
            name='SubOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('org_type', models.CharField(max_length=48)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('documents', models.ManyToManyField(related_name='organization_documents', to='core.DocumentFile')),
                ('org_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='innovosite.SubOrganization')),
                ('org_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suborganizations', to='innovosite.Innovosite')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='building_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovosite.Innovosite'),
        ),
        migrations.AddField(
            model_name='building',
            name='documents',
            field=models.ManyToManyField(related_name='building_documents', to='core.DocumentFile'),
        ),
    ]
