# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=48, null=True)),
                ('description', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Innovosite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
                ('address', models.TextField(null=True)),
                ('zipcode', models.IntegerField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('org_type', models.CharField(max_length=48)),
                ('description', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
                ('address', models.TextField(null=True)),
                ('org_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='innovosite.SubOrganization')),
                ('org_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovosite.Innovosite')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='building_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovosite.Innovosite'),
        ),
    ]
