# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovosite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovosite',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='site_documents', to='core.DocumentFile'),
        ),
    ]
