# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innovosite', '0002_auto_20160429_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborganization',
            name='org_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suborganizations', to='innovosite.Innovosite'),
        ),
    ]
