# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 20:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_cpvcode_innovotag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovouser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
